# Generated by Django 5.2.5 on 2025-08-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='is_active',
        ),
        migrations.AddField(
            model_name='devicereading',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.CharField(default=None, max_length=100, unique=True),
        ),
    ]
