# Generated by Django 5.2.5 on 2025-08-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_device_is_active_devicereading_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicereading',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='devicereading',
            name='is_active',
        ),
        migrations.AddField(
            model_name='devicereading',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='devicereading',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
