# Generated by Django 5.2.5 on 2025-08-26 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_timestamp_devicereading_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='device',
            name='properties',
        ),
        migrations.RemoveField(
            model_name='device',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='device',
            name='updated_at',
        ),
    ]
