# Generated by Django 5.2.5 on 2025-08-26 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_device_created_at_remove_device_properties_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicereading',
            old_name='data',
            new_name='properties',
        ),
    ]
