# Generated by Django 5.2.5 on 2025-09-01 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_data_devicereading_properties'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicereading',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='devicereading',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='api.device'),
        ),
    ]
